### ISSUE TITLE
You tried to hack my server using a webhook 

### ISSUE THREAD

**Issue by SugarFreeNoDiabetes** [Its-Vichy/Sezam#1]
Hello Mr.Vichy. I've seen you tried to hack my server! But, thankfully enough, you did not do anything, as it did not affect anything in my server and did not delete it. Thank you! Now i've made my server impossible to hack, try it, if you wish. :)

**Comment by Its-Vichy** [comment]
Wtf ?, its not me LMAO i think is just smart people use my tools to delete dumb kids token grabbers, don't cry
