### ISSUE TITLE
bro

### ISSUE THREAD

**Issue by dekrypted** [Its-Vichy/Sezam#3]
bro u just reskinned rdimo's pyextractor ur not fooling anyone

**Comment by Its-Vichy** [comment]
The fact was i have made this tool 1year ago + you seems to be to dumb for check https://github.com/Its-Vichy/Sezam/tree/main/Modules :p

**Comment by dekrypted** [comment]
omg I didnt even look at the date lfmao

yeah sorry im sped myb myb the ui just looked similar
